# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Covid-19 Tracking 
    url: 'https://www.covidradar24.org/web/dhafer.malouche/home'
    weight: 10
  - name: Biography
    url: '#about'
    weight: 40
  - name: Recent Publications
    url: '#publications'
    weight: 30
  - name: Courses
    url: 'courses/'
    weight: 20
  - name: Posts
    url: '#posts'
    weight: 30
  - name: CV
    url: "uploads/resume.pdf"
    weight: 50
  - name: Contact
    url: '#contact'
    weight: 60
